version: '2'
# https://github.com/go-task/task
tasks:
  svc:
    desc: "Build svc"
    dir: cmd/rg_svc/
    cmds:
      - go build
      - ./rg_svc
  gen:
    desc: "generate design"
    cmds:
      - goa gen github.com/jaredwarren/rg/design
  example:
    desc: "generate examples"
    cmds: 
      - goa example github.com/jaredwarren/rg/design
  # usage examples
  home:
    cmds:  
    - |
      curl -i \
      --request GET \
      http://localhost:8080/home
  list:
    cmds:  
    - |
      curl --header "Content-Type: application/json" \
      --request GET \
      http://localhost:8080/schedule
  create:
    desc: "create cron schedule"
    cmds:  
    - |
      curl -L --header "Content-Type: application/json" \
      --request POST \
      --data '{"name":"{{.name}}","cron":"{{.cron}}","color":"{{.color}}"}' \
      http://localhost:8080/schedule
  remove:
    cmds:  
    - |
      curl --header "Content-Type: application/json" \
      --request DELETE \
      http://localhost:8080/schedule/{{.id}}
  #Color
  set:
    cmds:  
    - |
      curl -L --header "Content-Type: application/json" \
      --request POST \
      --data '{"color":"{{.color}}"}' \
      http://localhost:8080/color
  get:
    cmds:  
    - |
      curl -L --header "Content-Type: application/json" \
      --request GET \
      http://localhost:8080/color